feat(frontend): Initializing Home/Summoner pages and navbar
PowerSpikeGG/PowerSpikeGG pull request #28
Opened 2017-02-27 13:40 UTC by bouillonpi

2017-02-27 14:24 UTC, FunkySayu commented
Please provide screen shots :)

2017-02-27 14:44 UTC, bouillonpi commented
SCREENSHOTS
- Home Page : https://ibb.co/fgmTGF
- Summoner Page : https://ibb.co/cqFzOv

2017-02-27 15:11 UTC, FunkySayu requested changes
Mostly formatting. FTR: at some points it would be nice to order your css rules.

```
/* bad */
.foo {
    height: 100px;
    background: #fff;
}

/* good */
.foo {
    background: #fff;
    height: 100px;
}

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/app.module.ts
Remove this blank line

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/app.module.ts
> +import { BrowserModule } from '@angular/platform-browser';
Some imports are formated as `{FooBar}` and some other as `{ FooBar }`. Choose one, and stick to it

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/app.module.ts
> +
Remove blank line

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/app.module.ts
> +import { PageNotFoundComponent } from "./page-not-found/page-not-found.component";
Quoting issue: from tslint: `" should be '`
Please refer to [this styleguide](https://github.com/Platypi/style_typescript#quotes) to know when to use `"` and `'` as string separator.

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/app.module.ts
> +import { HomeModule } from "./home/home.module";
Quoting issue

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/app.module.ts
> +import { NavbarComponent } from "./navbar/navbar.component";
Quoting issue

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/app.module.ts
> +import { SummonerModule } from "./summoner/summoner.module";
Quoting issue

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/app.routing.ts
>  import {ModuleWithProviders} from "@angular/core";
Quoting issue; Also please stick to your import style (`{<space>FooBar<space>}` or `{FooBar}`). Here and on all other imports.

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/app.module.ts
Most of your code have one space between imports and code. Remove this blank line.

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/home/home.module.ts
>  import {SearchBarComponent} from "./searchbar.component";
Quoting issue; Also please stick to your import style (`{<space>FooBar<space>}` or `{FooBar}`). Here and on all other imports.

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/home/home.module.ts
>  @NgModule({
Some other files are using a 4 space identation. Choose one, but stick with it :) I would suggest 2 spaces indentation.

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/home/searchbar.component.ts
> +import {Router} from "@angular/router";
Quoting issue; Also please stick to your import style ({<space>FooBar<space>} or {FooBar}). Here and on all other imports.

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/home/searchbar.component.ts
> +import { QuerySenderService } from '../services/query-sender.service';
Place your project imports below general modules imports, with one space separating them. For example:

```
import { Component, OnInit } from '@angular/core';

import { QuerySenderService } from '../services/query-sender.service';

/* My code */
```

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/home/searchbar.component.ts
> +      console.log("[INFO] Summoner Query sent: " + this.summonerQuery);
" should be '

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/home/searchbar.component.ts
> +    let logStr = '[ERROR] [QUERY SENDER SERVICE] ' + error;
You can avoid defining this variable here.
`console.log('[ERROR] [QUERY SENDER SERVICE] ' + error)`

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/navbar/navbar.component.html
> +      <li><a href="">PowerspikeGG</a></li>
is `href` necessary if empty?

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/services/query-sender.service.ts
> +import {Observable} from "rxjs";
Same as other imports

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/services/query-sender.service.ts
> +  sendSummonerQuery(summonerQuery: string): Observable<summonerQuery> {
It would be appreciable to get a doc here.

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/services/query-sender.service.ts
> +    let url = 'api/summoner?name='+summonerQuery;
`'api/summoner?name='+summonerQuery` => `'api/summoner?name=' + summonerQuery`

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/app/summoner/summoner.module.ts
> +import {SummonerComponent}   from './summoner.component';
Re-order imports (+ quoting on other ones)

2017-02-27 15:11 UTC, FunkySayu commented on powerspikegg/frontend/src/styles.css
> +
Remove blank line

2017-02-28 13:33 UTC, FunkySayu approved these changes
Really nice work here :)

2017-02-28 13:33 UTC, FunkySayu commented on powerspikegg/frontend/src/app/models/summonerData.ts
> +export interface summonerData {
From the [style guide](https://github.com/Platypi/style_typescript#interfaces)
>Interfaces should use UpperCamelCase.

2017-02-28 13:44 UTC, merged