Add checks on Python and WORKSPACE in git hooks
PowerSpikeGG/PowerSpikeGG pull request #49
Opened 2017-03-08 14:53 UTC by FunkySayu

2017-03-13 21:24 UTC, cassand requested changes

2017-03-13 21:24 UTC, cassand commented on WORKSPACE
> +    name = "com_github_oleiade_lane",
It seems this repository is added but not used

2017-03-13 21:24 UTC, cassand commented on WORKSPACE
> +    name = "com_github_oleiade_lane",
Just moved in fact, good to go

2017-03-13 21:24 UTC, cassand approved these changes

2017-03-13 21:26 UTC, cassand commented on devutils/git-hooks/pre-commit
> +    which pep8 > /dev/null || Log::Failure "pep8 not found. Install it with pip install pep8."
It may be useful to make a page with all the dependencies for each workflow

2017-03-14 08:32 UTC, FunkySayu commented on devutils/git-hooks/pre-commit
> +    which pep8 > /dev/null || Log::Failure "pep8 not found. Install it with pip install pep8."
What do you mean? A function checking if all dependencies are installed?

2017-03-23 15:54 UTC, merged