Provide an endpoint aggregating the average stats on the fetcher.
PowerSpikeGG/PowerSpikeGG pull request #70
Opened 2017-04-02 18:42 UTC by FunkySayu

2017-04-02 22:58 UTC, ArchangelX360 requested changes
"selectionned" ;) #revenge

2017-04-02 22:58 UTC, ArchangelX360 commented on powerspikegg/rawdata/fetcher/aggregator_test.py
> +        """Tests filter per champion on the average aggregation."""
Should be "per champion AND league" in comment.

2017-04-02 22:58 UTC, ArchangelX360 commented on powerspikegg/rawdata/fetcher/aggregator_test.py
> +        """Tests filter per champion on the average aggregation."""
Also, every "... played are selectionned." line needs to be re-written (I can't comment on these as it is not on this PR).

2017-04-02 23:40 UTC, FunkySayu commented
Fixed.

2017-04-03 00:10 UTC, ArchangelX360 approved these changes
LGTM.

2017-04-03 00:10 UTC, merged