Adding documentation for the development stack
PowerSpikeGG/PowerSpikeGG pull request #87
Opened 2017-04-03 23:49 UTC by FunkySayu

2017-04-04 01:49 UTC, cassand approved these changes

2017-04-04 23:33 UTC, cassand requested changes

2017-04-04 23:33 UTC, cassand commented on configure
> +    pip install --user numpy tensorflow grpcio
tensorflow is no longer needed

2017-04-05 00:02 UTC, ArchangelX360 requested changes

2017-04-05 00:02 UTC, ArchangelX360 commented on configure
> +    git submodule update
--init needed on first update

2017-04-05 00:02 UTC, ArchangelX360 commented on docs/dev-stack.md
> + - [npm][npm] >= 6.0.0
this is the Node requirement
npm is only ^4.4.4

2017-04-05 00:02 UTC, ArchangelX360 commented on docs/dev-stack.md
> +and bring the docker composed stack.
bring the docker composed stack **up**.

2017-04-05 00:50 UTC, FunkySayu commented
Should be good

2017-04-05 00:53 UTC, ArchangelX360 approved these changes

2017-04-05 00:53 UTC, ArchangelX360 commented on docs/dev-stack.md
> +    devutils/generate-docker-compose
./devutils/generate-docker-compose

2017-04-05 00:53 UTC, bouillonpi approved these changes

2017-04-05 00:55 UTC, cassand approved these changes

2017-04-05 00:56 UTC, merged